name: currency_converter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0+1
  localization: ^2.1.0
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/back_arrow_icon.png
    - assets/images/close_icon.png
    - assets/images/down_arrow_icon.png
    - assets/images/foward_arrow_icon.png
    - assets/images/refresh_icon.png
    - assets/images/scale_icon.png
    - assets/images/search_icon.png
    - assets/images/weight_icon.png
    - assets/images/pokeball.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
